#
# Automatically generated file; DO NOT EDIT.
# Android Device Configuration
#
CONFIG_TABLET=true
CONFIG_TV=

#
# Dalvik/ART Heap Configuration
#
CONFIG_DALVIK_VM_HEAPSIZE=256
CONFIG_DALVIK_VM_HEAPSTARTSIZE=8
CONFIG_DALVIK_VM_HEAPMAXFREE=8
CONFIG_DALVIK_VM_HEAPGROWTHLIMIT=96

#
# Image Configuration
#
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE=ext4
CONFIG_SYSTEMIMAGE_FS_EXT4=true
CONFIG_SYSTEMIMAGE_FS_SQUASHFS=
BOARD_SYSTEMIMAGE_PARTITION_SIZE=1200000000
TARGET_USERIMAGES_SPARSE_EXT_DISABLED=true
CONFIG_DEX_PREOPT=true
CONFIG_KERNEL=
TARGET_NO_KERNEL=true

#
# Device Support
#

#
# Graphics support
#
CONFIG_SW_GRAPHICS=true
CONFIG_WIFI=
CONFIG_ETHERNET=true
CONFIG_SENSOR=
